# fly.toml file

app = "tihiydomik"

[build]
  image = "python:3.8-slim"
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"
